language: php

php:
  - 7.1
  - 7.4

matrix:
  fast_finish: true

  include:
    - php: 7.4
      env: COVERAGE=1

    - php: 7.3
      env: CHECKS=1 DEFAULT=0

before_script:
  - phpenv rehash

install:
  - composer self-update
  - composer install --prefer-dist --no-interaction --dev
  - if [[ $CHECKS = 1 ]]; then composer stan-setup; fi

script:
  - if [[ $CHECKS != 1 && $COVERAGE != 1 ]]; then phpunit; fi

  - if [[ $COVERAGE = 1 ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=clover.xml || true; fi

  - if [[ $CHECKS = 1 ]]; then composer cs-check; fi
  - if [[ $CHECKS = 1 ]]; then composer stan; fi

after_success:
  - if [[ $COVERAGE = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
